FROM nginx:stable

COPY nginx.conf /etc/nginx/nginx.conf
COPY index.html  /usr/share/nginx/html

ENV NGINX_VERSION=1.2
COPY entrypoint.sh entrypoint.sh
RUN /bin/bash -c 'ls -la; chmod +x entrypoint.sh; ls -la'

ENTRYPOINT ["bash", "entrypoint.sh"]
